# Site settings
title: Michael's Headquarters
author: Michael Head
subtitle: On UX Design and Development
email: michaelehead@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michaelehead.com" # the base hostname & protocol for your site
twitter_username: michaelehead
github_username:  headquarters
linkedin_username: michaelehead

# Build settings
markdown: kramdown

# Defaults
defaults:
  -
    scope: 
        path: ""
        type: "posts"
    values:
        layout: "default"
        section: "blog"
  -
    scope: 
        path: ""
        type: "pages"
    values:
        layout: "default"