# Site settings
title: Michael's Headquarters
author: Michael Head
subtitle: On UX Design and Development
email: michaelehead@gmail.com
description: > #
  Michael Head is a UX-focused software engineer with more than 6 years of experience building awesome user experiences
  for small agencies, mid-sized companies, and Fortune 50 corporations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michaelehead.com" # the base hostname & protocol for your site
twitter_username: michaelehead
github_username:  headquarters
linkedin_username: michaelehead

# Build settings
markdown: kramdown

# Defaults
defaults:
  -
    scope:
        path: ""
        type: "posts"
    values:
        layout: "default"
        section: "blog"
  -
    scope:
        path: ""
        type: "pages"
    values:
        layout: "default"
